services:
  - type: web
    name: ustreamweb3-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/ustreamweb3-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
