#################################################################
# Example render.yaml                                           #
# Do not use this file directly! Consult it for reference only. #
#################################################################

previews:
  generation: manual  # Can also set to 'automatic' or 'off'

services:
  - name: ustreamweb3-backend
    type: web
    runtime: docker  # For Java apps, using Docker
    plan: starter # Use "starter" or "standard" for more resources
    branch: main
    buildCommand: ./mvnw clean package  # Build command for Maven
     # Command to run the application

    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://sql.freedb.tech:3306/freedb_ustreamweb3
      - key: SPRING_DATASOURCE_USERNAME
        value: freedb_ustreamweb3-users
      - key: SPRING_DATASOURCE_PASSWORD
        value: kAY9Y?9H$%9Kf@$
      - key: SPRING_PROFILES_ACTIVE
        value: prod  # Active Spring profile

    region: oregon  # Preferred region for deployment

databases:
  - name: my-database  # Placeholder for any future databases
    plan: free
    region: oregon

envVarGroups:
  - name: MyEnvironmentGroup
    envVars:
      - key: APP_SECRET
        generateValue: true  # Generates a random secret key for sensitive information
