services:
  - name: ustreamweb3-backend
    type: web
    runtime: docker  # For Java apps, you can specify 'docker' and include a Dockerfile
    plan: free  # Use "starter" or "standard" for more resources
    branch: main
    buildCommand: ./mvnw clean package  # Adjust this if using Gradle
    startCommand: java -jar target/ustreamweb3-backend-0.0.1-SNAPSHOT.jar  # Update to match your .jar name

    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://sql.freedb.tech:3306/freedb_ustreamweb3
      - key: SPRING_DATASOURCE_USERNAME
        value: freedb_ustreamweb3-users
      - key: SPRING_DATASOURCE_PASSWORD
        value: kAY9Y?9H$%9Kf@$
      - key: SPRING_PROFILES_ACTIVE
        value: prod  # or any other profile name you're using in production

    region: oregon  # Specify your preferred region: oregon, ohio, virginia, frankfurt, singapore

databases:
  - name: my-database  # Placeholder name for any future databases, if needed (e.g., for PostgreSQL)
    plan: free
    region: oregon

previews:
  generation: manual  # Can also set to 'automatic' or 'off'

envVarGroups:
  - name: MyEnvironmentGroup
    envVars:
      - key: APP_SECRET
        generateValue: true  # Generates a random secret key for sensitive information
